services:
  bot:
    build:
      context: ./apps/bot
      dockerfile: Dockerfile
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      MAIN_CHANNEL_ID: ${MAIN_CHANNEL_ID}
    restart: unless-stopped
  ui:
    build:
      context: ./apps/ui
      dockerfile: Dockerfile
    environment:
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_API_BASE_URL: ${API_BASE_URL}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      DISCORD_SUPERADMIN_ROLE_IDS: ${DISCORD_SUPERADMIN_ROLE_IDS}
      DISCORD_ADMIN_ROLE_IDS: ${DISCORD_ADMIN_ROLE_IDS}
      DISCORD_OPERATOR_ROLE_IDS: ${DISCORD_OPERATOR_ROLE_IDS}
      DISCORD_SUPPORT_ROLE_IDS: ${DISCORD_SUPPORT_ROLE_IDS}
      DISCORD_AUDITOR_ROLE_IDS: ${DISCORD_AUDITOR_ROLE_IDS}
    ports:
      - "3000:3000"
    depends_on:
      - api
      - bot

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      PANEL_BASE_URL: ${PANEL_BASE_URL}
    ports:
      - "8080:8080"
